export type Books = typeof books

export const books = [
  {
    title: "Morning Star",
    author: "Pierce Brown",
    image: "https://covers.openlibrary.org/b/id/0012401168-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2025-09-17",
  },
  {
    title: "Memory Police",
    author: "Yōko Ogawa",
    image: "https://covers.openlibrary.org/b/id/0013763988-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2025-05-08",
  },
  {
    title: "Golden Son",
    author: "Pierce Brown",
    image: "https://covers.openlibrary.org/b/id/0012047886-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2025-05-11",
  },
  {
    title: "Red Rising",
    author: "Pierce Brown",
    image: "https://covers.openlibrary.org/b/id/0008185003-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2025-04-29",
  },
  {
    title: "Tao Te Ching",
    author: "Lao Tzu (translated by Stephen Mitchell)",
    image: "https://covers.openlibrary.org/b/id/36638-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2025-03-27",
  },
  {
    title: "The Martian",
    author: "Andy Weir (narrated by Wil Wheaton)",
    image: "https://covers.openlibrary.org/b/id/14641755-L.jpg",
    status: "Read",
    type: "Media",
    media: "Audiobook",
    date: "2024-02-08",
  },
  {
    title: "The Dark Forest",
    author: "Liu Cixin",
    image: "https://covers.openlibrary.org/b/id/0012392944-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Book",
    date: "2024-03-12",
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    image: "https://covers.openlibrary.org/b/id/11212360-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2024-04-20",
  },
  {
    title: "I'm Glad My Mom Died",
    author: "Jennette McCurdy",
    image: "https://covers.openlibrary.org/b/id/13117595-L.jpg",
    status: "Read",
    type: "Media",
    media: "Audiobook",
    date: "2022-08-09",
  },
  {
    title: "We are Legion (We are Bob)",
    author: "Dennis E. Taylor",
    image: "https://covers.openlibrary.org/b/id/8421582-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Audiobook",
    date: "2024-05-18",
  },
  {
    title: "Three Body Problem",
    author: "Cixin Liu",
    image: "https://covers.openlibrary.org/b/id/9157544-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2022-06-22",
  },
  {
    title: "Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    image: "https://covers.openlibrary.org/b/id/12954148-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2023-07-10",
  },
  {
    title: "Tomorrow, Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    image: "https://covers.openlibrary.org/b/id/12859975-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Book",
    date: "2024-08-05",
  },
  {
    title: "No Longer Human",
    author: "Osamu Dazai",
    image: "https://covers.openlibrary.org/b/id/597940-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2021-09-14",
  },
  {
    title: "Inspired: How to Create Tech Products Customers Love",
    author: "Marty Cagan",
    image: "https://covers.openlibrary.org/b/id/13348591-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Book",
    date: "2024-10-08",
  },
  {
    title: "14 Habits of Highly Productive Developers",
    author: "Zeno Rocha",
    image: "https://m.media-amazon.com/images/I/719Siqxb0eL._SL1500_.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
    date: "2024-11-25",
  },
]
