export type Books = typeof books

export const books = [
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    image: "https://covers.openlibrary.org/b/id/11212360-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
  },
  {
    title: "I'm Glad My Mom Died",
    author: "Jennette McCurdy",
    image: "https://covers.openlibrary.org/b/id/13117595-L.jpg",
    status: "Read",
    type: "Media",
    media: "Audiobook",
  },
  {
    title: "We are Legion (We are Bob)",
    author: "Dennis E. Taylor",
    image: "https://covers.openlibrary.org/b/id/8421582-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Audiobook",
  },
  {
    title: "Three Body Problem",
    author: "Cixin Liu",
    image: "https://covers.openlibrary.org/b/id/9157544-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
  },
  {
    title: "Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    image: "https://covers.openlibrary.org/b/id/12954148-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
  },
  {
    title: "Tomorrow, Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    image: "https://covers.openlibrary.org/b/id/12859975-L.jpg",
    status: "DNF",
    type: "Media",
    media: "Book",
  },
  {
    title: "No Longer Human",
    author: "Osamu Dazai",
    image: "https://covers.openlibrary.org/b/id/597940-L.jpg",
    status: "Read",
    type: "Media",
    media: "Book",
  },
  {
    title: "Inspired: How to Create Tech Products Customers Love",
    author: "Marty Cagan",
    image: "https://covers.openlibrary.org/b/id/13348591-L.jpg",
    status: "Reading",
    type: "Media",
    media: "Book",
  },
  {
    title: "14 Habits of Highly Productive Developers",
    author: "Zeno Rocha",
    image: "https://m.media-amazon.com/images/I/719Siqxb0eL._SL1500_.jpg",
    status: "Reading",
    type: "Media",
    media: "Book",
  },
]
