export type Movies = typeof movies

export const movies = [
  {
    type: "Media",
    media: "Movie",
    title: "Thor: Love and Thunder",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Doctor Strange in the Multiverse of Madness",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//fwBl3J2aEXru6mrr9Xg8O99Iz2K.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Turning Red",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Midsommar",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Minions: The Rise of Gru",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Hereditary",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//p9fmuz2Oj3HtEJEqbIwkFGUhVXD.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Man from Toronto",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//uTCfTibqtk4f90cC59bLPMOmsfc.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "CODA",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
    status: "Watched",
    date: "2022-07-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Get Out",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    status: "Watched",
    date: "2022-07-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Top Gun",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
    status: "Watched",
    date: "2022-07-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Top Gun: Maverick",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    status: "Watched",
    date: "2022-07-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Her",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    status: "Watched",
    date: "2022-07-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Zathura: A Space Adventure",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//gDb5BW2NLqZ9cvg9nyzkZVvmgze.jpg",
    status: "Watched",
    date: "2022-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Little Miss Sunshine",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//cfVDxpSgP4J7wPavgZTm8KbEai6.jpg",
    status: "Watched",
    date: "2022-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Fight Club",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    status: "Watched",
    date: "2022-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Eternal Sunshine of the Spotless Mind",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    status: "Watched",
    date: "2022-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Whiplash",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    status: "Watched",
    date: "2022-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "X",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
    status: "Watched",
    date: "2022-07-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Sadness",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//mi5lh2brPMzuWYddyUKuCtcnjt1.jpg",
    status: "Watched",
    date: "2022-07-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Not Okay",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//x1q3FkqFHBkMeKnHiS6GYgdLvUs.jpg",
    status: "Watched",
    date: "2022-07-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Swan",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//rH19vkjAzCZ0HIUvrgB3rowm68h.jpg",
    status: "Watched",
    date: "2022-08-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "1917",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    status: "Watched",
    date: "2022-08-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nightcrawler",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Weathering with You",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//qgrk7r1fV4IjuoeiGS5HOhXNdLJ.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Your Name.",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//q719jXXEzOoYaps6babgKnONONX.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Neighbors",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//dyO9BQ4M4flTOAzP79rmsz61yAT.jpg",
    status: "Watched",
    date: "2022-08-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Legally Blonde",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//4ABNnmkVpzplrEVQWt1piITT0Ey.jpg",
    status: "Watched",
    date: "2022-08-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Prey",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
    status: "Watched",
    date: "2022-08-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Panther: Wakanda Forever",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Barbarian",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//idT5mnqPcJgSkvpDX7pJffBzdVH.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Don't Worry Darling",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//wjAJWfuE5OQm5zerlOAbTxdHFMV.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Bullet Train",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//j8szC8OgrejDQjjMKSVXyaAjw3V.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nope",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Enola Holmes 2",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Adam",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Guardians of the Galaxy Holiday Special",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    status: "Watched",
    date: "2022-11-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Love, Rosie",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//rpD0t7DhzJVadnzgxSYrqljQTL2.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Batman",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//74xTEgt7R36Fpooo50r9T25onhq.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Adam Project",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Spider-Man: No Way Home",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//5weKu49pzJCt06OPpjvT80efnQj.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Honor Society",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//61CZ4JxyaI462sFfLPhtyzRg4vv.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scary Movie",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//lRQiJXETkCnVVurHmglNvMXrZOx.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Where the Crawdads Sing",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//6h5OCqRnWH7Dcm4IeP4JypBdtuI.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Drive",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Guilty",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//m8aR1k35oZMOzZ1kYWUyt401mwq.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Gone Girl",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//lv5xShBIDPe7m4ufdlV0IAc7Avk.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Menu",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//v31MsWhF9WFh7Qooq6xSBbmJxoG.jpg",
    status: "Watched",
    date: "2023-01-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Puss in Boots: The Last Wish",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    status: "Watched",
    date: "2023-01-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Banshees of Inisherin",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
    status: "Watched",
    date: "2023-01-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Smile",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    status: "Watched",
    date: "2023-01-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "WALL·E",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    status: "Watched",
    date: "2023-01-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Devotion",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
    status: "Watched",
    date: "2023-01-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "TÁR",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "M3GAN",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    status: "Watched",
    date: "2023-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "House Party",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//KiyKR9m6h01eIvGObGmpt16U3F.jpg",
    status: "Watched",
    date: "2023-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Everything Everywhere All at Once",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    status: "Watched",
    date: "2023-01-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Babylon",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
    status: "Watched",
    date: "2023-02-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Ant-Man and the Wasp: Quantumania",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    status: "Watched",
    date: "2023-02-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Whale",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg",
    status: "Watched",
    date: "2023-02-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Women Talking",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//twUbb6Irktv0VEsJXQWJ3VKyxFX.jpg",
    status: "Watched",
    date: "2023-03-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "American Gangster",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//sX9idXDqRUxE5ffww3n3RV5gL55.jpg",
    status: "Watched",
    date: "2023-03-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Jojo Rabbit",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//7GsM4mtM0worCtIVeiQt28HieeN.jpg",
    status: "Watched",
    date: "2023-03-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Cocaine Bear",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    status: "Watched",
    date: "2023-03-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "BlacKkKlansman",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//8jxqAvSDoneSKRczaK8v9X5gqBp.jpg",
    status: "Watched",
    date: "2023-03-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Avatar: The Way of Water",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    status: "Watched",
    date: "2023-03-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Mockingjay – Part 2",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//lImKHDfExAulp16grYm8zD5eONE.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Catching Fire",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//vrQHDXjVmbYzadOXQ0UaObunoy2.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Mockingjay – Part 1",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tetris",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//4F2QwCOYHJJjecSvdOjStuVLkpu.jpg",
    status: "Watched",
    date: "2023-04-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Fresh",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//tlu71AgaL3EQBBCNGsAwZLPbV5D.jpg",
    status: "Watched",
    date: "2023-04-04",
  },
  {
    type: "Media",
    media: "Series",
    title: "Daisy Jones & the Six",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//ltfscPUljehY7IwGG85vij2TEbQ.jpg",
    status: "Watched",
    date: "2023-04-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Murder Mystery 2",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    status: "Watched",
    date: "2023-04-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Parasite",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    status: "Watched",
    date: "2023-04-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Creed III",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    status: "Watched",
    date: "2023-04-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Inside",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//dXsiWJWwGwYwOQ6DfYFt5pPBMwT.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Training Day",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//bUeiwBQdupBLQthMCHKV7zv56uv.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "BEEF",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//5dt2ojhQfX57zLrqlIZ6BbPeiQ.jpg",
    status: "Watched",
    date: "2023-04-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Guardians of the Galaxy Vol. 3",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    status: "Watched",
    date: "2023-05-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Shazam! Fury of the Gods",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg",
    status: "Watched",
    date: "2023-05-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scream VI",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
    status: "Watched",
    date: "2023-05-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Pearl",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//ulBLIBqvdnf4H6JBt0OpMCU1ECn.jpg",
    status: "Watched",
    date: "2023-05-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Evil Dead Rise",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
    status: "Watched",
    date: "2023-05-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Air",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg",
    status: "Watched",
    date: "2023-05-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Super Mario Bros. Movie",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    status: "Watched",
    date: "2023-05-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Donnie Darko",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg",
    status: "Watched",
    date: "2023-05-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "White Men Can't Jump",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//i83Ykng2HVY5EF043zMmeQdLUQY.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Big George Foreman",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//fdVd6thTstt0MQ4dUC1IXiOXpxv.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "A Star Is Born",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Series",
    title: "Queen Charlotte: A Bridgerton Story",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//kFSaVIlBRycGNfrLzJZX7dgSQ1o.jpg",
    status: "Watched",
    date: "2023-05-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "John Wick: Chapter 4",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    status: "Watched",
    date: "2023-05-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Sisu",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
    status: "Watched",
    date: "2023-05-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Inglourious Basterds",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    status: "Watched",
    date: "2023-06-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Spider-Man: Across the Spider-Verse",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    status: "Watched",
    date: "2023-06-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Lord of War",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//3MGQD4yXokufNlW1AyRXdiy7ytP.jpg",
    status: "Watched",
    date: "2023-06-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Django Unchained",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    status: "Watched",
    date: "2023-07-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Flash",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    status: "Watched",
    date: "2023-07-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Oppenheimer",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    status: "Watched",
    date: "2023-07-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Transformers: Rise of the Beasts",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    status: "Watched",
    date: "2023-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tenet",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
    status: "Watched",
    date: "2023-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Southpaw",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//kSQ49Fi3NVTqGGXILmxV2T2pdkG.jpg",
    status: "Watched",
    date: "2023-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "65",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500//rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
    status: "Watched",
    date: "2023-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Little Mermaid",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    status: "Watched",
    date: "2023-07-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Secret Invasion",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//8YDNwj9gsAQlcHQALPtjJipoGx8.jpg",
    status: "Watched",
    date: "2023-07-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dunkirk",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
    status: "Watched",
    date: "2023-07-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Elemental",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    status: "Watched",
    date: "2023-08-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Army of Thieves",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//iPTZGFmPs7HsXHYxiuxGolihjOH.jpg",
    status: "Watched",
    date: "2023-08-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Knives Out",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    status: "Watched",
    date: "2023-08-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Glass Onion",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    status: "Watched",
    date: "2023-08-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kill Bill: Vol. 1",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    status: "Watched",
    date: "2023-08-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kill Bill: Vol. 2",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg",
    status: "Watched",
    date: "2023-08-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Past Lives",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    status: "Watched",
    date: "2023-08-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "La La Land",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    status: "Watched",
    date: "2023-08-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "You Are So Not Invited to My Bat Mitzvah",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//ukpifWBW2xEmMtJX4bCpoNpWEr2.jpg",
    status: "Watched",
    date: "2023-09-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500//ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg",
    status: "Watched",
    date: "2023-09-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Barbie",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    status: "Watched",
    date: "2023-09-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tangled",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//ym7Kst6a4uodryxqbGOxmewF235.jpg",
    status: "Watched",
    date: "2023-09-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dungeons & Dragons: Honor Among Thieves",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg",
    status: "Watched",
    date: "2023-09-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Blue Beetle",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
    status: "Watched",
    date: "2023-09-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Bottoms",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//jeyTQrNEpyE1LZIgVlswYh3sc34.jpg",
    status: "Watched",
    date: "2023-09-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Talk to Me",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
    status: "Watched",
    date: "2023-09-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Mean Girls",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500//2ZkuQXvVhh45uSvkBej4S7Ix1NJ.jpg",
    status: "Watched",
    date: "2023-10-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Burial",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//9ssNSfNKpzZwhbFsnW3wa82m2sG.jpg",
    status: "Watched",
    date: "2023-10-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw X",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
    status: "Watched",
    date: "2023-10-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Clueless",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//8AwVTcgpTnmeOs4TdTWqcFDXEsA.jpg",
    status: "Watched",
    date: "2023-10-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//4da0TS3iQ1IzuyhDS8elgkmOfrN.jpg",
    status: "Watched",
    date: "2023-10-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw II",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//AwfBNpkedYcXt9BjGEYZf5g2s37.jpg",
    status: "Watched",
    date: "2023-10-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Five Nights at Freddy's",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//7BpNtNfxuocYEVREzVMO75hso1l.jpg",
    status: "Watched",
    date: "2023-10-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scott Pilgrim vs. the World",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500//g5IoYeudx9XBEfwNL0fHvSckLBz.jpg",
    status: "Watched",
    date: "2023-11-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
    status: "Watched",
    date: "2023-11-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Pain Hustlers",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//m0gM9jE1KmCkXZRqkeNYEQZdVsZ.jpg",
    status: "Watched",
    date: "2023-11-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Serenity",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500//hgWAcic93phg4DOuQ8NrsgQWiqu.jpg",
    status: "Watched",
    date: "2023-11-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Trolls Band Together",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//bkpPTZUdq31UGDovmszsg2CchiI.jpg",
    status: "Watched",
    date: "2023-11-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "How to Lose a Guy in 10 Days",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//2dlftyPz7mTYbrsPvTogyFmYd7d.jpg",
    status: "Watched",
    date: "2023-11-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Family Switch",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//fnRUCA0fjEb3kuIaTGogL7425IC.jpg",
    status: "Watched",
    date: "2023-12-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Killers of the Flower Moon",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500//dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    status: "Watched",
    date: "2023-12-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Priscilla",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//uDCeELWWpsNq7ErM61Yuq70WAE9.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Family Plan",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500//jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Leave the World Behind",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dream Scenario",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500//eMaAi8wTI5wON8pp33w3BDuGyZ8.jpg",
    status: "Watched",
    date: "2023-12-23",
  },
]
