export type Movies = typeof movies

export const movies = [
  {
    type: "Media",
    media: "Movie",
    title: "Midsommar",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Top Gun",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
    status: "Watched",
    date: "2022-07-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Man from Toronto",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/uTCfTibqtk4f90cC59bLPMOmsfc.jpg",
    status: "Watched",
    date: "2022-07-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Get Out",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    status: "Watched",
    date: "2022-07-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Turning Red",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Doctor Strange in the Multiverse of Madness",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Minions: The Rise of Gru",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Thor: Love and Thunder",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    status: "Watched",
    date: "2022-07-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Hereditary",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    status: "Watched",
    date: "2022-07-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "CODA",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
    status: "Watched",
    date: "2022-07-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Zathura: A Space Adventure",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/shUtIadbOk8BAWk4FR0LinbBUmR.jpg",
    status: "Watched",
    date: "2022-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Her",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/lEIaL12hSkqqe83kgADkbUqEnvk.jpg",
    status: "Watched",
    date: "2022-07-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Little Miss Sunshine",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/wKn7AJw730emlmzLSmJtzquwaeW.jpg",
    status: "Watched",
    date: "2022-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Fight Club",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    status: "Watched",
    date: "2022-07-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Eternal Sunshine of the Spotless Mind",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    status: "Watched",
    date: "2022-07-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Whiplash",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    status: "Watched",
    date: "2022-07-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "X",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
    status: "Watched",
    date: "2022-07-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Sadness",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/mi5lh2brPMzuWYddyUKuCtcnjt1.jpg",
    status: "Watched",
    date: "2022-07-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Not Okay",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/x1q3FkqFHBkMeKnHiS6GYgdLvUs.jpg",
    status: "Watched",
    date: "2022-07-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Swan",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/viWheBd44bouiLCHgNMvahLThqx.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Top Gun: Maverick",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    status: "Watched",
    date: "2022-07-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "1917",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Weathering with You",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/qgrk7r1fV4IjuoeiGS5HOhXNdLJ.jpg",
    status: "Watched",
    date: "2022-08-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Your Name.",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
    status: "Watched",
    date: "2022-08-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Panther: Wakanda Forever",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Don't Worry Darling",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/jOqxKIOC92BVyinYO1Fm73XY7Tc.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Neighbors",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/sN1RU08CMi8xkRIibremh3AOdgw.jpg",
    status: "Watched",
    date: "2022-08-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Barbarian",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Legally Blonde",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/9ohlMrJHQqKhfUKh7Zr3JQqHNLZ.jpg",
    status: "Watched",
    date: "2022-08-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Prey",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/h58U7d1OZyuWaCWMYvw4mfnv6H3.jpg",
    status: "Watched",
    date: "2022-08-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nightcrawler",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    status: "Watched",
    date: "2022-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nope",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Adam",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/rCtreCr4xiYEWDQTebybolIh6Xe.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Guardians of the Galaxy Holiday Special",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    status: "Watched",
    date: "2022-11-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Bullet Train",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/j8szC8OgrejDQjjMKSVXyaAjw3V.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Adam Project",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Enola Holmes 2",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
    status: "Watched",
    date: "2022-11-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Spider-Man: No Way Home",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Batman",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Honor Society",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/61CZ4JxyaI462sFfLPhtyzRg4vv.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Love, Rosie",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/rpD0t7DhzJVadnzgxSYrqljQTL2.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Where the Crawdads Sing",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/n1el846gLDXfhOvrRCsyvaAOQWv.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scary Movie",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/fVQFPRuw3yWXojYDJvA5EoFjUOY.jpg",
    status: "Watched",
    date: "2022-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Gone Girl",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/ts996lKsxvjkO2yiYG0ht4qAicO.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Guilty",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/m8aR1k35oZMOzZ1kYWUyt401mwq.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Drive",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    status: "Watched",
    date: "2022-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Menu",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg",
    status: "Watched",
    date: "2023-01-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Puss in Boots: The Last Wish",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/aV1KGO9X3S4kzqEptVDAvGjccql.jpg",
    status: "Watched",
    date: "2023-01-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Smile",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Banshees of Inisherin",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "WALL\u00b7E",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "T\u00c1R",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "M3GAN",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    status: "Watched",
    date: "2023-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "House Party",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/HesN5Mrqlq6oYTsmfFggIVEMwE.jpg",
    status: "Watched",
    date: "2023-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Babylon",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
    status: "Watched",
    date: "2023-02-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Whale",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg",
    status: "Watched",
    date: "2023-02-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Devotion",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
    status: "Watched",
    date: "2023-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Women Talking",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/wcTc9GveMMjAdHSlzdE0FaRCtqi.jpg",
    status: "Watched",
    date: "2023-03-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Everything Everywhere All at Once",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    status: "Watched",
    date: "2023-01-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "American Gangster",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/8sV6nWuKczuXRt0C6EWoXqJAj6G.jpg",
    status: "Watched",
    date: "2023-03-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Ant-Man and the Wasp: Quantumania",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    status: "Watched",
    date: "2023-02-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Cocaine Bear",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    status: "Watched",
    date: "2023-03-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "BlacKkKlansman",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/8jxqAvSDoneSKRczaK8v9X5gqBp.jpg",
    status: "Watched",
    date: "2023-03-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Jojo Rabbit",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/7GsM4mtM0worCtIVeiQt28HieeN.jpg",
    status: "Watched",
    date: "2023-03-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Catching Fire",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/qdXXEFGuLLfMWa1DGEkWFUo8Zwd.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Avatar: The Way of Water",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    status: "Watched",
    date: "2023-03-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Mockingjay \u2013 Part 2",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/7uLJCuK0ufoDklUdOORC8XanOKw.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tetris",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/4F2QwCOYHJJjecSvdOjStuVLkpu.jpg",
    status: "Watched",
    date: "2023-04-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: Mockingjay \u2013 Part 1",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/2hTPkBiXoMmrdtYgHtB9WU5dg80.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
    status: "Watched",
    date: "2023-03-31",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Murder Mystery 2",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Creed III",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Fresh",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/tlu71AgaL3EQBBCNGsAwZLPbV5D.jpg",
    status: "Watched",
    date: "2023-04-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Parasite",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Inside",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/dXsiWJWwGwYwOQ6DfYFt5pPBMwT.jpg",
    status: "Watched",
    date: "2023-04-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Daisy Jones & the Six",
    author: "",
    rating: 5.0,
    image: "",
    status: "Watched",
    date: "2023-04-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Training Day",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/bUeiwBQdupBLQthMCHKV7zv56uv.jpg",
    status: "Watched",
    date: "2023-04-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "BEEF",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/5dt2ojhQfX57zLrqlIZ6BbPeiQ.jpg",
    status: "Watched",
    date: "2023-04-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scream VI",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
    status: "Watched",
    date: "2023-05-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Shazam! Fury of the Gods",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg",
    status: "Watched",
    date: "2023-05-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Guardians of the Galaxy Vol. 3",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    status: "Watched",
    date: "2023-05-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Pearl",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/z5uIG81pXyHKg7cUFIu84Wjn4NS.jpg",
    status: "Watched",
    date: "2023-05-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Evil Dead Rise",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
    status: "Watched",
    date: "2023-05-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Air",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg",
    status: "Watched",
    date: "2023-05-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "White Men Can't Jump",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/i83Ykng2HVY5EF043zMmeQdLUQY.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Super Mario Bros. Movie",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    status: "Watched",
    date: "2023-05-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Big George Foreman",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/fdVd6thTstt0MQ4dUC1IXiOXpxv.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Donnie Darko",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/fhQoQfejY1hUcwyuLgpBrYs6uFt.jpg",
    status: "Watched",
    date: "2023-05-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "John Wick: Chapter 4",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    status: "Watched",
    date: "2023-05-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "A Star Is Born",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
    status: "Watched",
    date: "2023-05-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Queen Charlotte: A Bridgerton Story",
    author: "",
    rating: 5.0,
    image: "",
    status: "Watched",
    date: "2023-05-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Spider-Man: Across the Spider-Verse",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    status: "Watched",
    date: "2023-06-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Sisu",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
    status: "Watched",
    date: "2023-05-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Inglourious Basterds",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    status: "Watched",
    date: "2023-06-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Django Unchained",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/bV0rWoiRo7pHUTQkh6Oio6irlXO.jpg",
    status: "Watched",
    date: "2023-07-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Lord of War",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/3MGQD4yXokufNlW1AyRXdiy7ytP.jpg",
    status: "Watched",
    date: "2023-06-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Transformers: Rise of the Beasts",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    status: "Watched",
    date: "2023-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Flash",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    status: "Watched",
    date: "2023-07-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Oppenheimer",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    status: "Watched",
    date: "2023-07-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Southpaw",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/kSQ49Fi3NVTqGGXILmxV2T2pdkG.jpg",
    status: "Watched",
    date: "2023-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tenet",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
    status: "Watched",
    date: "2023-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "65",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
    status: "Watched",
    date: "2023-07-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Little Mermaid",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    status: "Watched",
    date: "2023-07-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Secret Invasion",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/8YDNwj9gsAQlcHQALPtjJipoGx8.jpg",
    status: "Watched",
    date: "2023-07-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dunkirk",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
    status: "Watched",
    date: "2023-07-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Elemental",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    status: "Watched",
    date: "2023-08-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Knives Out",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    status: "Watched",
    date: "2023-08-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Army of Thieves",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/4fVMognsmbogzkfY7DY0Bvn7h7Y.jpg",
    status: "Watched",
    date: "2023-08-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Glass Onion",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    status: "Watched",
    date: "2023-08-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kill Bill: Vol. 1",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    status: "Watched",
    date: "2023-08-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kill Bill: Vol. 2",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg",
    status: "Watched",
    date: "2023-08-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/kbnhvFPyXKCKLNhg1pkz6rXQ4Le.jpg",
    status: "Watched",
    date: "2023-09-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "La La Land",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    status: "Watched",
    date: "2023-08-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Past Lives",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/rzO71VFu7CpJMfF5TQNMj0d1lSV.jpg",
    status: "Watched",
    date: "2023-08-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "You Are So Not Invited to My Bat Mitzvah",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/ukpifWBW2xEmMtJX4bCpoNpWEr2.jpg",
    status: "Watched",
    date: "2023-09-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tangled",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/ym7Kst6a4uodryxqbGOxmewF235.jpg",
    status: "Watched",
    date: "2023-09-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Barbie",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    status: "Watched",
    date: "2023-09-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Blue Beetle",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
    status: "Watched",
    date: "2023-09-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dungeons & Dragons: Honor Among Thieves",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg",
    status: "Watched",
    date: "2023-09-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Bottoms",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/jeyTQrNEpyE1LZIgVlswYh3sc34.jpg",
    status: "Watched",
    date: "2023-09-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Mean Girls",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/alKvY5LuVcXraRBfi5UtVV8Ii6Y.jpg",
    status: "Watched",
    date: "2023-10-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Talk to Me",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
    status: "Watched",
    date: "2023-09-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Burial",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/9ssNSfNKpzZwhbFsnW3wa82m2sG.jpg",
    status: "Watched",
    date: "2023-10-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/4da0TS3iQ1IzuyhDS8elgkmOfrN.jpg",
    status: "Watched",
    date: "2023-10-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw X",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/u7Lp1Hi8aBS73jv4KRMIv5aK4ax.jpg",
    status: "Watched",
    date: "2023-10-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Clueless",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/8AwVTcgpTnmeOs4TdTWqcFDXEsA.jpg",
    status: "Watched",
    date: "2023-10-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scott Pilgrim vs. the World",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/g5IoYeudx9XBEfwNL0fHvSckLBz.jpg",
    status: "Watched",
    date: "2023-11-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Five Nights at Freddy's",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/4dKRTUylqwXQ4VJz0BS84fqW2wa.jpg",
    status: "Watched",
    date: "2023-10-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saw II",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/gTnaTysN8HsvVQqTRUh8m35mmUA.jpg",
    status: "Watched",
    date: "2023-10-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/lrkOYL5GBTFW9cgs9RlojxAcZZF.jpg",
    status: "Watched",
    date: "2023-11-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Trolls Band Together",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
    status: "Watched",
    date: "2023-11-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Pain Hustlers",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/m0gM9jE1KmCkXZRqkeNYEQZdVsZ.jpg",
    status: "Watched",
    date: "2023-11-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "How to Lose a Guy in 10 Days",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/2dlftyPz7mTYbrsPvTogyFmYd7d.jpg",
    status: "Watched",
    date: "2023-11-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Serenity",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/hgWAcic93phg4DOuQ8NrsgQWiqu.jpg",
    status: "Watched",
    date: "2023-11-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Family Switch",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/g8Gwitm4CtZBSYhLeSY4Z3Xwwcg.jpg",
    status: "Watched",
    date: "2023-12-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Priscilla",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Leave the World Behind",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Killers of the Flower Moon",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    status: "Watched",
    date: "2023-12-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Family Plan",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg",
    status: "Watched",
    date: "2023-12-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dream Scenario",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/2RSMu2iMDCdMKmvBWWvcmE8vjMj.jpg",
    status: "Watched",
    date: "2023-12-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Saltburn",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/zGTfMwG112BC66mpaveVxoWPOaB.jpg",
    status: "Watched",
    date: "2023-12-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "They Cloned Tyrone",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/hnzXoDaK346U4ByfvQenu2DZnTg.jpg",
    status: "Watched",
    date: "2024-01-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Eileen",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/x6kedRqcj8jH0cik9p1jzkDwZvM.jpg",
    status: "Watched",
    date: "2024-01-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Prisoners",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    status: "Watched",
    date: "2024-01-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Thanksgiving",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Nice Guys",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/clq4So9spa9cXk3MZy2iMdqkxP2.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Triangle of Sadness",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/k9eLozCgCed5FGTSdHu0bBElAV8.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "When Evil Lurks",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/iQ7G9LhP7NRRIUM4Vlai3eOxBAc.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Misery",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/23Y65uWaVMpqfbZTN3CT0aei4D5.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Amadeus",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/1n5VUlCqgmVax1adxGZm8oCFaKc.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Pianist",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    status: "Watched",
    date: "2024-01-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Creator",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/3dSivDtOuyxLDxPH4v2tcNG1fP7.jpg",
    status: "Watched",
    date: "2024-01-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Parent Trap",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/dNqgjqxHIdfsQRQL5XTujNfX9pj.jpg",
    status: "Watched",
    date: "2024-01-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Gladiator",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/w0YjBWVfu689txEXZG3xa4Aev3i.jpg",
    status: "Watched",
    date: "2024-01-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Boys in the Boat",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/ncJMztHprw3gLRAnDjNnnT23CIt.jpg",
    status: "Watched",
    date: "2024-01-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nobody",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
    status: "Watched",
    date: "2024-01-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "First Man",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/i91mfvFcPPlaegcbOyjGgiWfZzh.jpg",
    status: "Watched",
    date: "2024-01-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Wonka",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    status: "Watched",
    date: "2024-01-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Schindler's List",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    status: "Watched",
    date: "2024-01-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Thelma & Louise",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/vbRAGLzbC75QfiKD1lKjmnQGuph.jpg",
    status: "Watched",
    date: "2024-01-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Holdovers",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg",
    status: "Watched",
    date: "2024-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dallas Buyers Club",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/7Fdh7gUq3plvQqxRbNYhWvDABXA.jpg",
    status: "Watched",
    date: "2024-01-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Beekeeper",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    status: "Watched",
    date: "2024-02-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "American Fiction",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/57MFWGHarg9jid7yfDTka4RmcMU.jpg",
    status: "Watched",
    date: "2024-02-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Iron Claw",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/lsdismtCDga4vsKnmliz0h7CaZT.jpg",
    status: "Watched",
    date: "2024-02-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Anyone But You",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    status: "Watched",
    date: "2024-02-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Mean Girls",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/alKvY5LuVcXraRBfi5UtVV8Ii6Y.jpg",
    status: "Watched",
    date: "2024-02-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "As Above, So Below",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/oJZSajKLJkoTOzSZQN2ZwRnPwHZ.jpg",
    status: "Watched",
    date: "2024-02-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dune: Part Two",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    status: "Watched",
    date: "2024-03-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Ricky Stanicky",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/oJQdLfrpl4CQsHAKIxd3DJqYTVq.jpg",
    status: "Watched",
    date: "2024-03-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Argylle",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/siduVKgOnABO4WH4lOwPQwaGwJp.jpg",
    status: "Watched",
    date: "2024-03-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Marvels",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    status: "Watched",
    date: "2024-03-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Anatomy of a Fall",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
    status: "Watched",
    date: "2024-03-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Ella Enchanted",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/7AyNzwSEpJEG1gBdgwRfXi1cjs8.jpg",
    status: "Watched",
    date: "2024-03-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Zone of Interest",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    status: "Watched",
    date: "2024-03-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Road House",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/fDEdtS4P0gJsxHDIt8dG8TR5dx1.jpg",
    status: "Watched",
    date: "2024-03-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Spaceman",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/f46WvKEsBn98WJbPJcO47ZoKn6B.jpg",
    status: "Watched",
    date: "2024-03-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Late Night with the Devil",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/mu8LRWT9GHkfiyHm7kgxT6YNvMW.jpg",
    status: "Watched",
    date: "2024-04-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Hidden Figures",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/9lfz2W2uGjyow3am00rsPJ8iOyq.jpg",
    status: "Watched",
    date: "2024-03-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Immaculate",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/zyopv7D5j7cfswG0NYiA14qAdPC.jpg",
    status: "Watched",
    date: "2024-04-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kung Fu Panda 4",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/nqXsAaQsKw2gKpkfhIgjXNDRqg7.jpg",
    status: "Watched",
    date: "2024-04-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Rise of the Planet of the Apes",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/oqA45qMyyo1TtrnVEBKxqmTPhbN.jpg",
    status: "Watched",
    date: "2024-04-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dawn of the Planet of the Apes",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/kScdQEwS9jPEdnO23XjGAtaoRcT.jpg",
    status: "Watched",
    date: "2024-04-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Scoop",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/ib3H2ZSeVRTAmd7EtGWV31LswaZ.jpg",
    status: "Watched",
    date: "2024-04-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Dune",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    status: "Watched",
    date: "2024-04-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "War for the Planet of the Apes",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/mMA1qhBFgZX8O36qPPTC016kQl1.jpg",
    status: "Watched",
    date: "2024-04-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Flight",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/1AjXgBM2lkpG3FLQO0f6AK3Bi1e.jpg",
    status: "Watched",
    date: "2024-04-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Matilda",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/wYoDpWInsBEVSmWStnRH06ddoyk.jpg",
    status: "Watched",
    date: "2024-04-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Baby Reindeer",
    author: "",
    rating: 4.0,
    image: "",
    status: "Watched",
    date: "2024-04-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Hurt Locker",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/m2duGsKjBOl3BB8uFOTnRUzdEhg.jpg",
    status: "Watched",
    date: "2024-04-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Argo",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/m5gPWFZFIp4UJFABgWyLkbXv8GX.jpg",
    status: "Watched",
    date: "2024-04-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Departed",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    status: "Watched",
    date: "2024-04-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Beneath the Planet of the Apes",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/v1r5mBh9hxxWpvZl9G3cP7d1Mh9.jpg",
    status: "Watched",
    date: "2024-05-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "GoodFellas",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    status: "Watched",
    date: "2024-04-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Escape from the Planet of the Apes",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/AnbLVdUEroTfHTUVAJCxkL4R0IH.jpg",
    status: "Watched",
    date: "2024-05-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Fall Guy",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/e7olqFmzcIX5c23kX4zSmLPJi8c.jpg",
    status: "Watched",
    date: "2024-05-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Planet of the Apes",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/2r9iKnlSYEk4daQadsXfcjHfIjQ.jpg",
    status: "Watched",
    date: "2024-05-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Chicago",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/3ED8cWCXY9zkx77Sd0N5qMbsdDP.jpg",
    status: "Watched",
    date: "2024-05-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Civil War",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    status: "Watched",
    date: "2024-05-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "South Park: The End of Obesity",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/qjG4GAsQ89NpYzVtZ06aClxu5aG.jpg",
    status: "Watched",
    date: "2024-05-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Godzilla \u00d7 Kong: The New Empire",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    status: "Watched",
    date: "2024-05-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Poor Things",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    status: "Watched",
    date: "2024-05-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Godzilla Minus One",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    status: "Watched",
    date: "2024-05-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Furiosa: A Mad Max Saga",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    status: "Watched",
    date: "2024-06-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "End of Watch",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/pDeVKQICkcdwwjHxGj0MeS14YJ6.jpg",
    status: "Watched",
    date: "2024-06-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Lucy",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/kRbpUTRNm6QbLQFPFWUcNC4czEm.jpg",
    status: "Watched",
    date: "2024-07-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Margin Call",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/qtO57obCJuUBS0en3HLgFgZ19Xk.jpg",
    status: "Watched",
    date: "2024-06-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Moneyball",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/4yIQq1e6iOcaZ5rLDG3lZBP3j7a.jpg",
    status: "Watched",
    date: "2024-07-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "War Dogs",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg",
    status: "Watched",
    date: "2024-07-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kingdom of the Planet of the Apes",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    status: "Watched",
    date: "2024-07-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Bikeriders",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/qTb6sSRt8Pw96JTan8ezU2xO0FU.jpg",
    status: "Watched",
    date: "2024-07-11",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Deadpool & Wolverine",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    status: "Watched",
    date: "2024-07-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "MaXXXine",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
    status: "Watched",
    date: "2024-08-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Josee, the Tiger and the Fish",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/lNpZWdXC4HtXQ8nVo21gg7T9D6N.jpg",
    status: "Watched",
    date: "2024-07-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Fly Me to the Moon",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/gjk8YdXpItoC1in53FCrZMFIuBx.jpg",
    status: "Watched",
    date: "2024-08-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Despicable Me 4",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    status: "Watched",
    date: "2024-08-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Inside Out 2",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    status: "Watched",
    date: "2024-08-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "AVP: Alien vs. Predator",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/ySWu5bCnnmgV1cVacvFnFIhgOjp.jpg",
    status: "Watched",
    date: "2024-08-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Incendies",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/yH6DAQVgbyj72S66gN4WWVoTjuf.jpg",
    status: "Watched",
    date: "2024-08-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Incredible Hulk",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    status: "Watched",
    date: "2024-08-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Once Upon a Time... in Hollywood",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    status: "Watched",
    date: "2024-08-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Speed Racer",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/fxRIpx9Op9h71q3tvuabx4GryyP.jpg",
    status: "Watched",
    date: "2024-08-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Longlegs",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/1EwNyiiNFd863H4e8nWEzutnZD7.jpg",
    status: "Watched",
    date: "2024-08-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Kinds of Kindness",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/50lPmjIpDs8gKfgK7fPIeKzpllh.jpg",
    status: "Watched",
    date: "2024-08-28",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Color Purple",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/h5bqIxM8GO4TewJ0u6Rzkg58ssJ.jpg",
    status: "Watched",
    date: "2024-09-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Trap",
    author: "",
    rating: 1.5,
    image: "https://image.tmdb.org/t/p/w500/jwoaKYVqPgYemFpaANL941EF94R.jpg",
    status: "Watched",
    date: "2024-09-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Brother Bear",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/otptPbEY0vBostmo95xwiiumMJm.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Treasure Planet",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/zMKatZ0c0NCoKzfizaCzVUcbKMf.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Rebel Ridge",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/xEt2GSz9z5rSVpIHMiGdtf0czyf.jpg",
    status: "Watched",
    date: "2024-09-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "How to Train Your Dragon: The Hidden World",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Shark Tale",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/r08DpyPyhXcJTfNZAICNGMzcQ8l.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Madagascar",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/zMpJY5CJKUufG9OTw0In4eAFqPX.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tarzan",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/bTvHlcqiOjGa3lFtbrTLTM3zasY.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Visit",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/hDrToKMpKYTdwdpOhshL8ko6WVp.jpg",
    status: "Watched",
    date: "2024-09-13",
  },
  {
    type: "Media",
    media: "Movie",
    title: "L\u00e9on: The Professional",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Emoji Movie",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/60bTx5z9zL1AqCjZ0gmWoRMJ6Bb.jpg",
    status: "Watched",
    date: "2024-09-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Mr. & Mrs. Smith",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/kjD700RtyhveN3ZbOnSvUSne0Qj.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Me Before You",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/Ia3dzj5LnCj1ZBdlVeJrbKJQxG.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Help",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/3kmfoWWEc9Vtyuaf9v5VipRgdjx.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "X-Men: The Last Stand",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Tropic Thunder",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/zAurB9mNxfYRoVrVjAJJwGV3sPg.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Uglies",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/jaUu9zHtbcFwrB5Y1DNYE09HMex.jpg",
    status: "Watched",
    date: "2024-09-16",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Passengers",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/oZpdONg32luHu0g8HcysuPgSlIK.jpg",
    status: "Watched",
    date: "2024-09-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Marie Antoinette",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/cybXGmv8Rjd5Os8Xml6YxMBQ0Zt.jpg",
    status: "Watched",
    date: "2024-09-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Coherence",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/ezUtb9m5DeLwL2gxi4gktzNCvQv.jpg",
    status: "Watched",
    date: "2024-09-17",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Transformers One",
    author: "",
    rating: 4.5,
    image: "https://image.tmdb.org/t/p/w500/iRCgqpdVE4wyLQvGYU3ZP7pAtUc.jpg",
    status: "Watched",
    date: "2024-10-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Wolfs",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/vOX1Zng472PC2KnS0B9nRfM8aaZ.jpg",
    status: "Watched",
    date: "2024-09-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Blink Twice",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/lZGOK0I2DJSRlEPNOAFTSNxSjDD.jpg",
    status: "Watched",
    date: "2024-09-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Speak No Evil",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/6NwAlU6ZH6ua3sYpFAUpUnoKUmi.jpg",
    status: "Watched",
    date: "2024-10-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Alien: Romulus",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    status: "Watched",
    date: "2024-10-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Substance",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/evdF1vmLzuzH8EFblqAXBXWRGSi.jpg",
    status: "Watched",
    date: "2024-10-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Rush",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/5hpcfL3WH5ArSPUlfD4E1TtaOd0.jpg",
    status: "Watched",
    date: "2024-11-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Woman of the Hour",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/nc9ZqrJFbcUdlMg9lxXXtJb24jU.jpg",
    status: "Watched",
    date: "2024-10-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Platform 2",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/tvIpBg12IIA5Dr9Sjn38ygS1vQp.jpg",
    status: "Watched",
    date: "2024-10-07",
  },
  {
    type: "Media",
    media: "Movie",
    title: "We Live in Time",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/oeDNBgnlGF6rnyX1P1K8Vl2f3lW.jpg",
    status: "Watched",
    date: "2024-12-02",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Cube",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/iNwm6fpDqQ4WjwhYI8EW6LPklod.jpg",
    status: "Watched",
    date: "2024-11-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "13 Going on 30",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/iNZdSIfhSCMtRILDNyhLn8UKeSG.jpg",
    status: "Watched",
    date: "2024-12-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Wicked",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
    status: "Watched",
    date: "2024-11-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Roman J. Israel, Esq.",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/epTCHVcyLkT8Aqt08Ki3PWC2sUh.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Wizard of Oz",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/pfAZFD7I2hxW9HCChTuAzsdE6UX.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Lady Bird",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Miss Peregrine's Home for Peculiar Children",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/CIlbMFOfYDj0MP23hsIYhFGrL6.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Fast and the Furious",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/gqY0ITBgT7A82poL9jv851qdnIb.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "A Nonsense Christmas with Sabrina Carpenter",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/w6gBjvivsWwTbvz0bBAIxszOnWL.jpg",
    status: "Watched",
    date: "2024-12-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Senna",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/w5YwpRUYr0dIyzMM3eGMB6ZakXz.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Ready or Not",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/oJD9KQFoObZmxAS1je56SIFVNJt.jpg",
    status: "Watched",
    date: "2024-12-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Maze Runner",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/ode14q7WtDugFDp78fo9lCsmay9.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Transformers",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/lkZ9gqCEjzX85lKR6Jjd1uGAXNp.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Green Book",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
    status: "Watched",
    date: "2024-12-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Midway",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/hj8pyoNnynGeJTAbl7jcLZO8Uhx.jpg",
    status: "Watched",
    date: "2024-12-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Carry-On",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/sjMN7DRi4sGiledsmllEw5HJjPy.jpg",
    status: "Watched",
    date: "2024-12-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Anora",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
    status: "Watched",
    date: "2024-12-20",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Flipped",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/6zDYFigohwncqFL00MKbFV01dWb.jpg",
    status: "Watched",
    date: "2024-12-10",
  },
  {
    type: "Media",
    media: "Movie",
    title: "It's What's Inside",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/32Lfs4nbLehgbXI8VTeYg5jgIQt.jpg",
    status: "Watched",
    date: "2024-12-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Knock at the Cabin",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
    status: "Watched",
    date: "2025-01-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Set It Up",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/7omfwqiiMld9EnUps3Uk9YZLy6g.jpg",
    status: "Watched",
    date: "2024-12-12",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Happiness for Beginners",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/rK4jb2t3J98IXjY9O3nc8bX9yqt.jpg",
    status: "Watched",
    date: "2025-01-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Look Back",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/4f2EcNkp1Mvp9wE5w7HKxcmACWg.jpg",
    status: "Watched",
    date: "2025-01-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Six Triple Eight",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/7tvAnzZj9e9AjdoHaN9jshm2Cjw.jpg",
    status: "Watched",
    date: "2024-12-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Dangers in My Heart",
    author: "",
    rating: 4.5,
    image: "",
    status: "Watched",
    date: "2025-01-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Y2K",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/qndubIQalyxBJI5EBNZKGXEX74q.jpg",
    status: "Watched",
    date: "2024-12-27",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Who Framed Roger Rabbit",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/lYfRc57Kx9VgLZ48iulu0HKnM15.jpg",
    status: "Watched",
    date: "2025-01-21",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Heretic",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/fr96XzlzsONrQrGfdLMiwtQjott.jpg",
    status: "Watched",
    date: "2025-02-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Companion",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
    status: "Watched",
    date: "2025-02-22",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Hunger",
    author: "",
    rating: 1.5,
    image: "https://image.tmdb.org/t/p/w500/56rnpFxsI6LBY0EeQzLam2hMznt.jpg",
    status: "Watched",
    date: "2025-02-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Nosferatu",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
    status: "Watched",
    date: "2025-03-04",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Irishman",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
    status: "Watched",
    date: "2025-03-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Brutalist",
    author: "",
    rating: 3.5,
    image: "https://image.tmdb.org/t/p/w500/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
    status: "Watched",
    date: "2025-03-05",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Sonic the Hedgehog 3",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
    status: "Watched",
    date: "2025-03-14",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Da 5 Bloods",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/yx4cp1ljJMDSFeEex0Zjv45b55E.jpg",
    status: "Watched",
    date: "2025-03-06",
  },
  {
    type: "Media",
    media: "Movie",
    title: "White Boy Rick",
    author: "",
    rating: 1.5,
    image: "https://image.tmdb.org/t/p/w500/tIyqAObXHVHpJmbpun95d5iYlMx.jpg",
    status: "Watched",
    date: "2025-03-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "EuroTrip",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/iLdO4PwbZCCQSa9rchZMwuJm9xe.jpg",
    status: "Watched",
    date: "2025-03-15",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Cyberpunk: Edgerunners",
    author: "",
    rating: 4.5,
    image: "",
    status: "Watched",
    date: "2025-03-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Captain America: Brave New World",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    status: "Watched",
    date: "2025-03-19",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Adolescence",
    author: "",
    rating: 3.5,
    image: "",
    status: "Watched",
    date: "2025-03-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Mickey 17",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg",
    status: "Watched",
    date: "2025-04-01",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Monkey",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
    status: "Watched",
    date: "2025-03-29",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Devil Wears Prada",
    author: "",
    rating: 5.0,
    image: "https://image.tmdb.org/t/p/w500/OfFMqWQDZ4SlLtHiofyRoLjXdX.jpg",
    status: "Watched",
    date: "2025-04-03",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Gorge",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
    status: "Watched",
    date: "2025-04-08",
  },
  {
    type: "Media",
    media: "Movie",
    title: "No Hard Feelings",
    author: "",
    rating: 1.5,
    image: "https://image.tmdb.org/t/p/w500/gD72DhJ7NbfxvtxGiAzLaa0xaoj.jpg",
    status: "Watched",
    date: "2025-04-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Gladiator II",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    status: "Watched",
    date: "2025-04-09",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Mirror: B\u00eate Noire",
    author: "",
    rating: 3.5,
    image: "",
    status: "Watched",
    date: "2025-04-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Mirror: Nosedive",
    author: "",
    rating: 4.0,
    image: "",
    status: "Watched",
    date: "2025-04-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Mirror: Common People",
    author: "",
    rating: 4.0,
    image: "",
    status: "Watched",
    date: "2025-04-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Conclave",
    author: "",
    rating: 3.0,
    image: "https://image.tmdb.org/t/p/w500/l4WXg5oQPK6GVlISKQNIUGb8rKJ.jpg",
    status: "Watched",
    date: "2025-04-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Black Mirror: Plaything",
    author: "",
    rating: 3.0,
    image: "",
    status: "Watched",
    date: "2025-04-18",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Memoirs of a Geisha",
    author: "",
    rating: 1.0,
    image: "https://image.tmdb.org/t/p/w500/9twKlPKD5Qd2EXX8lohW4zL8zQ8.jpg",
    status: "Watched",
    date: "2025-04-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Novocaine",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg",
    status: "Watched",
    date: "2025-04-23",
  },
  {
    type: "Media",
    media: "Movie",
    title: "iHostage",
    author: "",
    rating: 0.5,
    image: "https://image.tmdb.org/t/p/w500/tn3Ckxyc7OWXnhMPkiIBvqLdFC6.jpg",
    status: "Watched",
    date: "2025-04-24",
  },
  {
    type: "Media",
    media: "Movie",
    title: "The Fabelmans",
    author: "",
    rating: 4.0,
    image: "https://image.tmdb.org/t/p/w500/h7llKkqkkJtJrTOaDLuVeUYDQ7I.jpg",
    status: "Watched",
    date: "2025-04-26",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Venom: The Last Dance",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
    status: "Watched",
    date: "2025-04-25",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Life",
    author: "",
    rating: 2.0,
    image: "https://image.tmdb.org/t/p/w500/wztfli5NgYDgurVgShNflvnyA3Z.jpg",
    status: "Watched",
    date: "2025-04-30",
  },
  {
    type: "Media",
    media: "Movie",
    title: "Zoolander",
    author: "",
    rating: 2.5,
    image: "https://image.tmdb.org/t/p/w500/1IOLMlNKSoo3FToVGYV1PjE3ehn.jpg",
    status: "Watched",
    date: "2025-04-25",
  },
];
