export const tools = {
  development: [
    {
      name: 'React',
      info: 'A JavaScript library for building user interfaces.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png',
      url: 'https://reactjs.org/',
    },
    {
      name: 'JavaScript',
      info: 'A high-level, interpreted programming language that conforms to the ECMAScript specification.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/1200px-JavaScript-logo.png',
      url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    },
    {
      name: 'Rust',
      info: 'A systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/1200px-Rust_programming_language_black_logo.svg.png',
      url: 'https://www.rust-lang.org/',
    },
    {
      name: 'Java',
      info: 'A class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.',
      icon: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/1200px-Java_programming_language_logo.svg.png',
      url: 'https://www.java.com/en/',
    },
    {
      name: 'Go',
      info: 'An open source programming language that makes it easy to build simple, reliable, and efficient software.',
      icon: 'https://cdn-icons-png.flaticon.com/512/919/919838.png',
      url: 'https://golang.org/',
    },
    {
      name: 'Python',
      info: 'A high-level, general-purpose programming language that is widely used in web development, scientific computing, and data analysis.',
      icon: 'https://cdn-icons-png.flaticon.com/512/5968/5968350.png',
      url: 'https://www.python.org/',
    },
    {
      name: 'Express',
      info: 'Express is a minimalist web framework for Node.js.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Expressjs.png/600px-Expressjs.png',
      url: 'https://expressjs.com/',
    },
    {
      name: 'MongoDB',
      info: 'MongoDB is a cross-platform document-oriented database program.',
      icon: 'https://cdn.iconscout.com/icon/free/png-256/mongodb-226029.png',
      url: 'https://www.mongodb.com/',
    },
    {
      name: 'PostgreSQL',
      info: 'PostgreSQL is a free and open-source relational database management system emphasizing extensibility and SQL compliance.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png',
      url: 'https://www.postgresql.org/',
    },
    {
      name: 'MySQL',
      info: 'MySQL is a free and open-source relational database management system.',
      icon: 'https://cdn.iconscout.com/icon/free/png-256/mysql-19-1174939.png',
      url: 'https://www.mysql.com/',
    },
    {
      name: 'Next.js',
      info: 'Next.js is a React-based framework for building server-rendered or statically-exported React applications.',
      icon: 'https://pbs.twimg.com/profile_images/1565710214019444737/if82cpbS_400x400.jpg',
      url: 'https://nextjs.org/',
    },
    {
      name: 'Git',
      info: 'Git is a distributed version control system for tracking changes in source code during software development.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Git-logo.svg/1200px-Git-logo.svg.png',
      url: 'https://git-scm.com/',
    },
    {
      name: 'Neovim',
      info: 'Neovim is a free and open-source text editor that aims to be a successor to the vim editor.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Neovim-mark.svg',
      url: 'https://neovim.io/',
    },
    {
      name: 'Docker',
      info: 'Docker is a containerization platform used for creating, deploying, and running applications.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Docker_%28container_engine%29_logo.png',
      url: 'https://www.docker.com/',
    },
    {
      name: 'Linux',
      info: 'Linux is a free and open-source operating system kernel used in many devices and servers worldwide.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/1200px-Tux.svg.png',
      url: 'https://www.linux.org/',
    },
  ],
  writing: [
    {
      name: 'Obsidian',
      info: 'Obsidian is a markdown note-taking app that allows users to create, link, and organize their notes.',
      icon: 'https://d33wubrfki0l68.cloudfront.net/294812798daac8df0fc70bf31928ba93102aff35/ef0e7/assets/images/tool-icons/obsidian.png',
      url: 'https://obsidian.md/',
    },
    {
      name: 'Notion',
      info: 'Notion is a productivity and organization tool that combines elements of a to-do list, note-taking, and project management.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Notion-logo.svg/1024px-Notion-logo.svg.png',
      url: 'https://www.notion.so/',
    },
    {
      name: 'mem.ai',
      info: 'mem.ai is an artificial intelligence-powered note-taking and organization tool.',
      icon: 'https://storage.googleapis.com/mem-public-assets/sq-f.jpg',
      url: 'https://mem.ai/',
    },
    {
      name: 'Google Docs',
      info: 'Google Docs is a cloud-based word processing program that allows users to create and edit documents online.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Google_Docs_logo_%282014-2020%29.svg',
      url: 'https://docs.google.com/',
    },
  ],
  editing: [
    {
      name: 'Figma',
      info: 'Figma is a cloud-based vector graphics editor and prototyping tool',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg',
      url: 'https://www.figma.com/',
    },
    {
      name: 'Photoshop',
      info: 'A powerful graphics editing software used for creating and editing images and designs.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Adobe_Photoshop_CC_icon.svg/512px-Adobe_Photoshop_CC_icon.svg.png?20200616073617',
      url: 'https://www.adobe.com/products/photoshop.html',
    },
    {
      name: 'Lightroom',
      info: 'A photo editing and management software used for organizing, editing, and sharing photos.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Adobe_Photoshop_Lightroom_CC_logo.svg/512px-Adobe_Photoshop_Lightroom_CC_logo.svg.png?20200616120137',
      url: 'https://www.adobe.com/products/photoshop-lightroom.html',
    },
    {
      name: 'Canva',
      info: 'A graphic design platform used for creating social media graphics, presentations, and other visual content.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Canva_logo.png?20200528174955',
      url: 'https://www.canva.com/',
    },
  ],
  etc: [
    {
      name: 'Mozilla Thunderbird',
      info: 'A free, open-source email and news client developed by the Mozilla Foundation.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Thunderbird_Logo%2C_2018.svg/512px-Thunderbird_Logo%2C_2018.svg.png?20180806181730',
      url: 'https://www.thunderbird.net/',
    },
    {
      name: 'Firefox',
      info: 'A free, open-source web browser developed by the Mozilla Foundation.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Firefox_brand_logo%2C_2019.svg/512px-Firefox_brand_logo%2C_2019.svg.png?20190616045834',
      url: 'https://www.mozilla.org/en-US/firefox/',
    },
    {
      name: 'Safari',
      info: 'A web browser developed by Apple Inc. and included as the default browser in all Apple products.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Safari_browser_logo.svg/234px-Safari_browser_logo.svg.png?20220831120132',
      url: 'https://www.apple.com/safari/',
    },
    {
      name: 'GitHub Desktop',
      info: 'A free, open-source Git client for Windows and Mac, developed by GitHub Inc.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Github-desktop-logo-symbol.svg/128px-Github-desktop-logo-symbol.svg.png?20200316183539',
      url: 'https://desktop.github.com/',
    },
    {
      name: 'Gmail',
      info: 'A free email service developed by Google.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gmail_icon_%282020%29.svg/512px-Gmail_icon_%282020%29.svg.png?20221017173631',
      url: 'https://www.gmail.com/',
    },
    {
      name: 'iCloud Mail',
      info: 'A free email service developed by Apple and included with every iCloud account.',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mail_%28iOS%29.svg/600px-Mail_%28iOS%29.svg.png?20141024222707',
      url: 'https://www.icloud.com/mail',
    },
  ],
};
